### PR TITLE
Parameterisation of secondary ice formation

### LINKED ISSUE #152: Add parameteriation of secondary ice
### What is the feature/what would you like to discuss?

 Parameterisation of secondary ice formation obtained from Georgia Sotiropoulou, developed from WRF and implemented in the Forces version of NorESM2. Changed files: micro_mg2_0.F90. New file module_random_forests.F90. Also changed namelist settings

### Is there anyone in particular you want to be part of this conversation?

_No response_

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes

### PR DESCRIPTION
**Pull request by oyvindseland**
Summary: Added new and extended parameterisation of secondary ice formation.

Contributors: @oyvindseland 

Reviewers: @gold2718 

Purpose of changes:   #152  Add parameteriation of secondary ice

Github PR URL: https://github.com/NorESMhub/CAM/pull/165

Changes made to build system: None

Changes made to the namelist: 5 new namelist parameters
- `rafsip_on`: If .true., compute secondary ice production using random forests method, Default: .false.
- `forestfileALL`: ML parameters for the forestALL RFR model, Default: None
- `forestfileBRDS`: ML parameters for the forestBRDS RFR model., Default: None
- `forestfileBRHM`: ML parameters for the forestBRHM RFR model., Default: None
- `forestfileBR`: ML parameters for the forestBR RFR model., Default: None
- `forestfileBRwarm`: ML parameters for the forestBRwarm RFR model., Default: None

Changes to the defaults for the boundary datasets: 5 ASCII files for reading in AI results used for calculating secondary ice formation.

Substantial timing or memory changes: None

Code changes to micro_mg2.0.F90 and added new subroutine module_random_forests.F90
Parameterisation is independent of Oslo-Aero and will in principle also work with MAM4.

1) New module contains random forest regressors for calculations of secondary ice formation for different physical domains (e.g. temperature ranges)
2) The main microphysics module is modified to include the new fluxes; the old limited parameterisation removed ; ice particle delimiter takes into account the new fluxes
3) The parameterisation is governed by  a logical rafsip_on. It is hardcoded and set to .true. Should be included as a namelist option.
4) The name of the files are hardcoded into the routine. The commit also include a  subroutine sec_ice_readnl that was used for reading in the file names from CAM namelist in project Forces simulations.

Georgakaki, P., &amp; Nenes, A. (2024). RaFSIP: Parameterizing ice multiplication in models using a machine learning approach. Journal of Advances in Modeling Earth Systems, 16, e2023MS003923.
https://doi.org/10.1029/2023MS003923

Only tested with compset NF2000climo at Betzy. Tested that the logical parameter set to .false. using the same model set-up give bit-identical results to model code built directly from the noresm2_3_develop branch

Issues addressed by this PR: Completes #152 for noresm2_3_develop

closes #152

### CODE REVIEW

**Comment by gold2718** [comment]
@oyvindseland, what is supposed to happen if `rafsip_on = .true.` but `do_cldice = .false.`?

**Comment by oyvindseland** [comment]
I need to check it in more details but I thought that they should be independent of each other? Secondary ice formation does not require aerosols.

**Comment by gold2718** [comment]
> I need to check it in more details but I thought that they should be independent of each other? Secondary ice formation does not require aerosols.

Thanks, I just want to make sure the code behaves that way.

**Comment by oyvindseland** [comment]
It is not critical that it works without do_cldice, but more general is always nice

File: src/NorESM/micro_mg2_0.F90 [hunk 1]
```diff
@@ -1636,6 +1770,240 @@ subroutine micro_mg_tend ( &
         !in fact, nothing in this entire file makes nsubc nonzero.
         nsubc(:,k) = 0._r8
 
+
+
+        IF (rafsip_on) THEN
```
Comment (gold2718) [inline src/NorESM/micro_mg2_0.F90:1755]: This block is only executed if `do_cldice == .true.`. Is that intentional?

File: src/NorESM/micro_mg2_0.F90
Comment (gold2718) [inline src/NorESM/micro_mg2_0.F90:1]: Can we get rid of `#ifndef NORESM2_ICE_DELIMITER` on line 2529, the `#else` clause beginning on line 2552. and the associated comments?

**Review by gold2718 — COMMENTED** [review]
I have a question about removing an ifdef.

File: src/NorESM/micro_mg2_0.F90
Comment (oyvindseland) [reply src/NorESM/micro_mg2_0.F90:1]: I need to check the code structure a bit since I realized that I did not fully understand the negation (infdef)
Does it mean ifndef  NORESM2_ICE_DELIMITER as if not ice delimiter as in noresm2, i.e. use the corrected version?

**Comment by oyvindseland** [comment]
I finally got around to check the do_cldice and I see now that it is actually a check if MG parameterisation should be used, not only hetfreez, which have a different logical variable. 
--> rafsip_on should only be included if do_cldice == true . 

It might not be required but I have no idea what would happen then.

File: src/NorESM/micro_mg2_0.F90
Comment (gold2718) [reply src/NorESM/micro_mg2_0.F90:1]: This logic is from the NorESM2.1 code. By default, `NORESM2_ICE_DELIMITER` is _not_ set. You have to uncomment out the line above (`#define NORESM2_ICE_DELIMITER`) to get back to the NorESM2 behavior. We added this logic to NorESM2.1 because the model was more in balance that way. However, because the plan is to tune NorESM2.3 (at least a bit), I do not think we need this logic (to allow the NorESM2.0 behavior) anymore. Thoughts?

Comment (oyvindseland) [reply src/NorESM/micro_mg2_0.F90:1]: I agree that the test should be removed.

**Comment by gold2718** [comment]
@oyvindseland: We need a test for this scheme. What NorESM2.3 compset do you suggest?

**Comment by oyvindseland** [comment]
It does not really matter but if we are going to tune the model N1850 is as good as anything else. The impact is more or less the same for both present dat and pre-industrial climate.

**Review by gold2718 — APPROVED** [review]
Looks good now.
